apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-zdmr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zdmr-space/argocd-demo-zdmr.git
    targetRevision: HEAD
    path: overlays/plex/zdmr
    kustomize:
      valuesFile: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
