apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: plex
  namespace: argocd
spec:
  description: Plex Media Server project
  sourceRepos:
    - 'https://github.com/zdmr-space/argocd-demo-zdmr.git'
  destinations:
    - namespace: plex
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-zdmr
  namespace: argocd
spec:
  project: plex
  sources:
  - repoURL: https://github.com/zdmr-space/argocd-demo-zdmr.git
    targetRevision: HEAD
    releaseName: plex
    path: overlays/plex/   
    helm:
      valueFiles:
      - zdmr/base.yaml      
      - zdmr/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
