# ###
#
# Its better practice to install CRD's manually for the control
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
# kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.84.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
#
# ###

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-appset
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - name: zdmr
            cluster: https://kubernetes.default.svc
      - git:
          repoURL: https://github.com/zdmr-space/argocd-demo-zdmr.git
          revision: HEAD
          directories:
          - path: overlays/prometheus/*
  template:
    metadata:
      name: prometheus-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/zdmr-space/argocd-demo-zdmr.git
        targetRevision: HEAD
        path: overlays/prometheus/
        helm:
          valueFiles:
          - values.yaml
          - '{{name}}/values.yaml'
      destination:
        server: '{{cluster}}'
        namespace: monitoring-{{name}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true