apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemonitors
  namespace: argocd
spec:
  destination:
    namespace: monitoring-zdmr
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/zdmr-space/argocd-demo-zdmr.git
    targetRevision: HEAD
    path: overlays/prometheus/zdmr/servicemonitor
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true