server:
  ha:
    enabled: false
  standalone:
    enabled: true
  extraEnvironmentVars:
    VAULT_LOCAL_CONFIG: |
      {
        "ui": true,
        "listener": [{
          "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": 1
          }
        }],
        "storage": {
          "raft": {
            "path": "/vault/data"
          }
        },
        "seal": {
          "kubernetes": {
            "secret_namespace": "vault",
            "secret_name": "vault-unseal-secret"
          }
        }
      }
  dataStorage:
    enabled: true
    size: 1Gi
