commonLabels:
  app: demo

resources:
- values.yaml

helmCharts:
  - name: plex-media-server
    repo: https://github.com/plexinc/pms-docker
    version: 1.1.1
    releaseName: plex
    includeCRDs: true