apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: plex-media-server
    repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    version: 1.1.1
    releaseName: plex
    namespace: plex
    valuesFile: values.yaml

resources: []
