apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  project: default
  source:
    repoURL: https://github.com/YOUR-USER/argocd-files.git
    path: environments/k3s-test-cluster/vault
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
