apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-operator
  project: default
  source:
    repoURL: https://github.com/zdmr-space/argocd-demo-zdmr.git
    path: environments/k3s-test-cluster/vault-operator
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
