version: "3.8"

services:
  k3s:
    image: rancher/k3s:v1.33.2-k3s1
    container_name: k3s
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./kubeconfig:/output
    ports:
      - "6443:6443"     # Kubernetes API
      - "8080:8080"     # ArgoCD UI (per Port-Forward)
      - "443:443"       
    command: server