namePrefix: zdmr-
commonLabels:
  variant: zdmr
bases:
- ../base
patchesStrategicMerge:
- values.yaml

helmCharts:
  - name: plex-media-server
    repo: https://github.com/plexinc/pms-docker
    version: 1.1.1
    releaseName: plex
    includeCRDs: true