apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    release: prometheus  # <- Muss zu deinem Prometheus Helm-Release passen!
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      targetPort: 8082
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server-metrics
  namespace: argocd
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
      app.kubernetes.io/component: server
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      targetPort: 8083
      path: /metrics
      interval: 30s
