apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: helm-kustomize
      init:
        command: [sh, -c]
        args: ["helm dependency build && kustomize edit add resource helm-template && kustomize build ."]
      generate:
        command: [sh, -c]
        args: ["kustomize build ."]