plex-media-server:
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - host: plex.zdmr.arpa
      paths:
      - path: /
        pathType: Prefix
    tls: []